service:
  name: 'ygo-lambda'

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - './**'

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3100

provider:
  name: aws
  runtime: nodejs10

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - '*'

functions:
  status:
    handler: build/handlers/status/status.status
    package:
      include:
        - build/handlers/status/status.*
    events:
      - http:
          path: /status
          method: get
          cors: true

  ygoDeckGetAll:
    handler: build/handlers/ygodeck/get.all
    package:
      include:
        - build/handlers/ygodeck/get.*
    events:
      - http:
          path: /ygodeck/getAll
          method: get
          cors: true
